In [2]:
import h5py
import numpy as np
from PIL import Image
import os
import matplotlib.pyplot as plt

In [3]:
paviaPCA1 = Image.open('images/pavia_university/PCA/paviaPCA1.png')
paviaPCA2 = Image.open('images/pavia_university/PCA/paviaPCA2.png')
paviaPCA3 = Image.open('images/pavia_university/PCA/paviaPCA3.png')
paviaPCA4 = Image.open('images/pavia_university/PCA/paviaPCA4.png')

In [29]:
npPaviaPCA1 = np.array(paviaPCA1)
npPaviaPCA2 = np.array(paviaPCA2)
npPaviaPCA3 = np.array(paviaPCA3)
npPaviaPCA4 = np.array(paviaPCA4)

npPaviaPCA1

array([[22, 19, 15, ..., 32, 33, 31],
       [19, 12,  8, ..., 35, 33, 30],
       [17, 10,  5, ..., 38, 36, 34],
       ..., 
       [40, 40, 36, ..., 23, 23, 24],
       [36, 43, 42, ..., 26, 26, 24],
       [36, 42, 45, ..., 26, 26, 26]], dtype=uint8)

In [26]:
mean_0 = Image.open('/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/mean_0.jpg')
npmean_0 = np.array(mean_0)

mean_1 = Image.open('/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/mean_1.jpg')
npmean_1 = np.array(mean_1)

mean_2 = Image.open('/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/mean_2.jpg')
npmean_2 = np.array(mean_2)

mean_3 = Image.open('/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/mean_3.jpg')
npmean_3 = np.array(mean_3)


npmean_0

array([[42, 42, 42, 42, 42, 42, 42, 42, 41],
       [42, 42, 42, 42, 42, 42, 42, 42, 41],
       [42, 42, 42, 42, 42, 42, 42, 42, 41],
       [41, 41, 41, 41, 41, 41, 41, 41, 40],
       [41, 41, 41, 41, 41, 41, 41, 41, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [39, 40, 40, 41, 41, 40, 40, 39, 39]], dtype=uint8)

<h2>KONTROL 1</h2>

In [31]:
npPaviaPCA1.shape

(610, 340)

In [48]:
#Benim Merkezi(9,454) olan yamam
i=9
j=454
my_input_patch = npPaviaPCA1[j-4:j+5, i-4:i+5] #[450:459, 5:14]
my_input_patch

array([[40, 42, 44, 46, 48, 54, 58, 36, 22],
       [40, 42, 45, 46, 47, 49, 55, 57, 33],
       [43, 45, 49, 49, 48, 49, 51, 59, 43],
       [44, 47, 56, 50, 44, 45, 46, 53, 59],
       [43, 44, 40, 26, 34, 44, 45, 47, 58],
       [43, 42, 36, 32, 40, 44, 46, 48, 54],
       [44, 44, 43, 42, 42, 44, 46, 48, 50],
       [44, 44, 43, 43, 44, 45, 46, 48, 50],
       [45, 45, 44, 43, 44, 46, 46, 47, 48]], dtype=uint8)

In [49]:
my_PCA1_patch = [None] * 1
my_PCA1_patch[0] = np.array(my_input_patch).astype(np.float)


PCA1_mean = [None] * 1
PCA1_mean[0] = np.array(npmean_0).astype(np.float)

PCA1_train_patches = [None]  * 1                       
PCA1_train_patches[0] = np.subtract(my_PCA1_patch[0], PCA1_mean[0])

#benim patch'den Erhan Hoca'nın mean'i çıkartıyorum
PCA1_train_patches[0]

array([[ -2.,   0.,   2.,   4.,   6.,  12.,  16.,  -6., -19.],
       [ -2.,   0.,   3.,   4.,   5.,   7.,  13.,  15.,  -8.],
       [  1.,   3.,   7.,   7.,   6.,   7.,   9.,  17.,   2.],
       [  3.,   6.,  15.,   9.,   3.,   4.,   5.,  12.,  19.],
       [  2.,   3.,  -1., -15.,  -7.,   3.,   4.,   6.,  18.],
       [  3.,   2.,  -4.,  -8.,   0.,   4.,   6.,   8.,  15.],
       [  4.,   4.,   3.,   2.,   2.,   4.,   6.,   8.,  11.],
       [  4.,   4.,   3.,   3.,   4.,   5.,   6.,   8.,  11.],
       [  6.,   5.,   4.,   2.,   3.,   6.,   6.,   8.,   9.]])

In [42]:
#Erhan Hoca'nın Merkezi(9,454) olan yaması
i='9'
j='454'
lbl = '2'
filename = "/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/train/patch_{x}_{y}_{label}.h5".format(x=i,y=j,label=lbl)
f = h5py.File(filename, 'r')
f['data'][0][0]

array([[  4.,   3.,   0.,   2.,   9.,  15.,  10.,   0., -18.],
       [ -4.,   0.,   1.,   1.,   4.,   9.,  10.,   8., -10.],
       [ -3.,   5.,   9.,   5.,   2.,   6.,  13.,  16.,   4.],
       [  2.,   9.,  11.,   4.,  -1.,   3.,   9.,  13.,  17.],
       [  0.,   2.,  -1.,  -6.,  -6.,  -1.,   3.,   3.,  18.],
       [  0.,  -1.,  -4.,  -6.,  -2.,   6.,   7.,   4.,  14.],
       [  4.,   4.,   2.,   0.,   3.,  10.,  11.,   8.,  11.],
       [  5.,   7.,   6.,   2.,   2.,   5.,   7.,   5.,  11.],
       [  6.,   4.,   4.,   3.,   3.,   5.,   6.,   8.,   9.]])

<b>Kontrol 1'de benim yamam'dan Erhan Hoca'nın mean'i çıktığımda Erhan Hoca'nın çıktısını bulmayı bekliyordum.<br/>Hatalı çıkması benim yamamım yanlış konumda olduğunu gösterebilir ama aşağıdaki yamaya göre konumumda doğru, öleyse fark nereden oluşuyor? </b>

In [85]:
#Benim Merkezi(9,454) olan yamam
i=9
j=454
my_input_patch = npPaviaPCA1[j-4:j+5, i-4:i+5] #[450:459, 5:14]
my_input_patch

array([[40, 42, 44, 46, 48, 54, 58, 36, 22],
       [40, 42, 45, 46, 47, 49, 55, 57, 33],
       [43, 45, 49, 49, 48, 49, 51, 59, 43],
       [44, 47, 56, 50, 44, 45, 46, 53, 59],
       [43, 44, 40, 26, 34, 44, 45, 47, 58],
       [43, 42, 36, 32, 40, 44, 46, 48, 54],
       [44, 44, 43, 42, 42, 44, 46, 48, 50],
       [44, 44, 43, 43, 44, 45, 46, 48, 50],
       [45, 45, 44, 43, 44, 46, 46, 47, 48]], dtype=uint8)

<h2>KONTROL 2</h2>

In [91]:
#Benim (9,454) noktasındaki hdf5
i='9'
j='454'
lbl = '2'
filename = "/home/yavuz/caffe/data/paviaUni_PCA_yama/train/train_{x}_{y}_{label}.hdf5".format(x=i,y=j,label=lbl)
f = h5py.File(filename, 'r')
my_output_patch = f['data'][0][0]
my_output_patch

array([[  0.,   2.,   4.,   6.,   8.,  14.,  18.,  -4., -18.],
       [  0.,   2.,   5.,   6.,   7.,   9.,  15.,  17.,  -7.],
       [  3.,   5.,   9.,   9.,   8.,   9.,  11.,  19.,   3.],
       [  4.,   7.,  16.,  10.,   4.,   5.,   6.,  13.,  19.],
       [  3.,   4.,   0., -14.,  -6.,   4.,   5.,   7.,  18.],
       [  3.,   2.,  -4.,  -8.,   0.,   4.,   6.,   8.,  14.],
       [  4.,   4.,   3.,   2.,   2.,   4.,   6.,   8.,  10.],
       [  4.,   4.,   3.,   3.,   4.,   5.,   6.,   8.,  10.],
       [  5.,   5.,   4.,   3.,   4.,   6.,   6.,   7.,   8.]])

In [92]:
#pav = paviaPCA1_pad
pav = npPaviaPCA1 #paddingsiz

r=9
c = (pav.shape[0] - (r-1))*(pav.shape[1] - (r-1))
PCA1_patches = [None] * c
k=0
for z in [pav[i:i+r,j:j+r] for i in xrange(pav.shape[0] - r + 1) for j in xrange(pav.shape[1] - r + 1)]:
    PCA1_patches[k] = z
    #print z
    k+=1
    
len(PCA1_patches)    

199864

In [93]:
my_mean_patch_pca1 = np.uint8(np.mean(PCA1_patches,axis=0))
my_mean_patch_pca1

array([[40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40]], dtype=uint8)

In [94]:
my_output_patch + my_mean_patch_pca1

array([[ 40.,  42.,  44.,  46.,  48.,  54.,  58.,  36.,  22.],
       [ 40.,  42.,  45.,  46.,  47.,  49.,  55.,  57.,  33.],
       [ 43.,  45.,  49.,  49.,  48.,  49.,  51.,  59.,  43.],
       [ 44.,  47.,  56.,  50.,  44.,  45.,  46.,  53.,  59.],
       [ 43.,  44.,  40.,  26.,  34.,  44.,  45.,  47.,  58.],
       [ 43.,  42.,  36.,  32.,  40.,  44.,  46.,  48.,  54.],
       [ 44.,  44.,  43.,  42.,  42.,  44.,  46.,  48.,  50.],
       [ 44.,  44.,  43.,  43.,  44.,  45.,  46.,  48.,  50.],
       [ 45.,  45.,  44.,  43.,  44.,  46.,  46.,  47.,  48.]])

In [95]:
my_input_patch

array([[40, 42, 44, 46, 48, 54, 58, 36, 22],
       [40, 42, 45, 46, 47, 49, 55, 57, 33],
       [43, 45, 49, 49, 48, 49, 51, 59, 43],
       [44, 47, 56, 50, 44, 45, 46, 53, 59],
       [43, 44, 40, 26, 34, 44, 45, 47, 58],
       [43, 42, 36, 32, 40, 44, 46, 48, 54],
       [44, 44, 43, 42, 42, 44, 46, 48, 50],
       [44, 44, 43, 43, 44, 45, 46, 48, 50],
       [45, 45, 44, 43, 44, 46, 46, 47, 48]], dtype=uint8)

<b>Ben kendi ile kendi hdf5 çıktımın doğruluğunu kontrol ettim.<b>

<h2>KONTROL 3</h2>

In [100]:
my_input_patch

array([[40, 42, 44, 46, 48, 54, 58, 36, 22],
       [40, 42, 45, 46, 47, 49, 55, 57, 33],
       [43, 45, 49, 49, 48, 49, 51, 59, 43],
       [44, 47, 56, 50, 44, 45, 46, 53, 59],
       [43, 44, 40, 26, 34, 44, 45, 47, 58],
       [43, 42, 36, 32, 40, 44, 46, 48, 54],
       [44, 44, 43, 42, 42, 44, 46, 48, 50],
       [44, 44, 43, 43, 44, 45, 46, 48, 50],
       [45, 45, 44, 43, 44, 46, 46, 47, 48]], dtype=uint8)

In [102]:
#Erhan Hoca'nın Merkezi(9,454) olan yaması
i='9'
j='454'
lbl = '2'
filename = "/home/yavuz/caffe/data/paviaUni_PCA_yama_erchan_hoca/train/patch_{x}_{y}_{label}.h5".format(x=i,y=j,label=lbl)
f = h5py.File(filename, 'r')
PCA1_patch = f['data'][0][0]
PCA1_patch

array([[  4.,   3.,   0.,   2.,   9.,  15.,  10.,   0., -18.],
       [ -4.,   0.,   1.,   1.,   4.,   9.,  10.,   8., -10.],
       [ -3.,   5.,   9.,   5.,   2.,   6.,  13.,  16.,   4.],
       [  2.,   9.,  11.,   4.,  -1.,   3.,   9.,  13.,  17.],
       [  0.,   2.,  -1.,  -6.,  -6.,  -1.,   3.,   3.,  18.],
       [  0.,  -1.,  -4.,  -6.,  -2.,   6.,   7.,   4.,  14.],
       [  4.,   4.,   2.,   0.,   3.,  10.,  11.,   8.,  11.],
       [  5.,   7.,   6.,   2.,   2.,   5.,   7.,   5.,  11.],
       [  6.,   4.,   4.,   3.,   3.,   5.,   6.,   8.,   9.]])

In [103]:
my_PCA1_input_patch = [None] * 1
my_PCA1_input_patch[0] = np.array(my_input_patch).astype(np.float)


PCA1_output_patch = [None] * 1
PCA1_output_patch[0] = np.array(PCA1_patch).astype(np.float)

PCA1_mean_patches = [None]  * 1                       
PCA1_mean_patches[0] = np.subtract(my_PCA1_input_patch[0], PCA1_output_patch[0])

#benim patch'den Erhan Hoca'nın hdf5'i çıkartıyorum. 
PCA1_mean_patches[0]

array([[ 36.,  39.,  44.,  44.,  39.,  39.,  48.,  36.,  40.],
       [ 44.,  42.,  44.,  45.,  43.,  40.,  45.,  49.,  43.],
       [ 46.,  40.,  40.,  44.,  46.,  43.,  38.,  43.,  39.],
       [ 42.,  38.,  45.,  46.,  45.,  42.,  37.,  40.,  42.],
       [ 43.,  42.,  41.,  32.,  40.,  45.,  42.,  44.,  40.],
       [ 43.,  43.,  40.,  38.,  42.,  38.,  39.,  44.,  40.],
       [ 40.,  40.,  41.,  42.,  39.,  34.,  35.,  40.,  39.],
       [ 39.,  37.,  37.,  41.,  42.,  40.,  39.,  43.,  39.],
       [ 39.,  41.,  40.,  40.,  41.,  41.,  40.,  39.,  39.]])

<b>Benim Merkezi(9,454) olan yamam'dan, Erhan Hoca'nın hdf5'i çıkartıyorum. Erhan Hoca'nın mean'in çıkmasını bekliyorum. Ama aşağıdaki Erhan Hoca'nın mean'den farklı çıkıyor.</b>

In [104]:
npmean_0

array([[42, 42, 42, 42, 42, 42, 42, 42, 41],
       [42, 42, 42, 42, 42, 42, 42, 42, 41],
       [42, 42, 42, 42, 42, 42, 42, 42, 41],
       [41, 41, 41, 41, 41, 41, 41, 41, 40],
       [41, 41, 41, 41, 41, 41, 41, 41, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 39],
       [39, 40, 40, 41, 41, 40, 40, 39, 39]], dtype=uint8)